---
name: Feature Request
about: Somethig is missing? 
title: ''
labels: enhancement
assignees: ''

---

<!-- Looking for help? Please visit our official forum at https://forum.aeon-php.org/ - github issues are only for bug reports -->

**Describe the feature**
A clear and concise description of what the feature should do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about how you are going to use that feature and why do you think others will benefit from it as well.
